# Generated by Django 2.1.7 on 2019-07-12 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('org_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('org_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(default='', max_length=100)),
                ('project_type', models.CharField(default='', max_length=100)),
                ('assigned_to', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('org_id', models.IntegerField(default=1)),
            ],
        ),
    ]
