# Generated by Django 2.1.7 on 2019-07-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='org_id',
            field=models.IntegerField(default=1),
        ),
    ]
